micronaut:
  application:
    name: mn-products
  openapi:
    property:
      naming:
        strategy: KEBAB_CASE
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      openapi-explorer:
        paths: classpath:META-INF/swagger/views/openapi-explorer
        mapping: /openapi-explorer/**
  security:
    authentication: bearer
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: changeThisSecretToALongSecuredString

my:
  api:
    version: 1.0.0
    description: "Service to fetch and manage all available products."